### POST CREATE PRODUCT
POST  http://localhost:8000 
Content-Type: application/json

{
    "name":"tea",
    "description":"nice cup of tea",
    "price":3.25,
    "sku":"killer-werewolf-hercules"
}


### GET PRODUCTS 
GET http://localhost:8000/ 

### PUT PRODUCTS 
PUT http://localhost:8000/3
Content-Type: application/json

{
    "name":"Double Espresso",
    "description":"very strong",
    "price":6.99,
    "sku":"fjf123"
}
