### POST CREATE PRODUCT
POST  http://localhost:8000 
Content-Type: application/json

{
    "id":1,
    "name":"tea",
    "description":"nice cup of tea",
    "price":3.25
}


### GET PRODUCTS 
GET http://localhost:8000/ 

### PUT PRODUCTS 
PUT http://localhost:8000/3
Content-Type: application/json

{
    "name":"Green Tea",
    "description":"nice cup of green tea",
    "price":4.99
}
